name: My-GitHubAction-Basic

on:
  push:
    
jobs:
  my_testing:
    runs-on: ubuntu-latest
  
    steps:
    - name: Git clone my repository
      uses: actions/checkout@v1
      
    - name: Install python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'
        
    - name: Install selenium
      run: pip install selenium==3.14.0  
      
    - name: Install pytest
#       uses: actions/setup-pytest@v1
      run: pip install pytest
      
    - name: View repository files
      run: ls -a
          
    - name: Run test 1
      run: pytest -v -s test_1.py
    
